spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daily_dictation
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: 21130312@st.hcmuaf.edu.vn
    password: gxsyfagknzvrdypr
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport.protocol: smtp
        debug: true

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 401126444153-1id05mb7bhses2uo8r5ol2qf3uu1uht4.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

cloudinary:
  cloud-name: XZTV5FQX
  api-key: 941627642784641
  api-secret: f5hyo9oDf4iM03fehOMrld7ASgg

vnpay:
  tmnCode: XZTV5FQX
  hashSecret: W4POYTPG3PVBONGLUDRNS5N2UG42P6NB
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/api/payment/vnpay-return

jwt:
  signerKey: "A7IHNV7cpx/zw7pnj/O/W3QxSTJF+3Uy+ld4l5U7zvHTfoaXEEipRVUMUwkLx5aQ"


