spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/daily_dictation"
    username: root
    password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  cloudinary:
    cloud-name: dc3o5kumf
    api-key: 941627642784641
    api-secret: f5hyo9oDf4iM03fehOMrld7ASgg
jwt:
  signerKey: "A7IHNV7cpx/zw7pnj/O/W3QxSTJF+3Uy+ld4l5U7zvHTfoaXEEipRVUMUwkLx5aQ"
